ports:
  - port: 8000
    onOpen: ignore
    visibility: public
    name: Server
  - port: 3306
    onOpen: ignore
    name: MySQL Database
  - port: 6379
    onOpen: ignore
    name: Redis

image:
  file: .gitpod.Dockerfile
tasks:
  - init: cargo build
    command: |
      bash scripts/gitpod.sh;
      cargo watch -x run

vscode:
  extensions:
    - rust-lang.rust-analyzer